openapi: 3.0.3
info:
  title: Simple Test API
  version: 1.0.0
  description: A simple API for testing without references

paths:
  /users:
    get:
      summary: List all users
      operationId: listUsers
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            minimum: 0
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                required:
                  - users
                properties:
                  users:
                    type: array
                    items:
                      type: object
                      required:
                        - id
                        - username
                        - email
                      properties:
                        id:
                          type: integer
                        username:
                          type: string
                          minLength: 3
                          maxLength: 50
                        email:
                          type: string
                          format: email
                        age:
                          type: integer
                          minimum: 0
                          maximum: 150
                  total:
                    type: integer

    post:
      summary: Create a new user
      operationId: createUser
      parameters:
        - name: x-api-key
          in: header
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
              properties:
                username:
                  type: string
                  minLength: 3
                  maxLength: 50
                email:
                  type: string
                  format: email
                password:
                  type: string
                  minLength: 8
                age:
                  type: integer
                  minimum: 13
                  maximum: 150
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  - username
                  - email
                properties:
                  id:
                    type: integer
                  username:
                    type: string
                  email:
                    type: string
                  createdAt:
                    type: string
                    format: date-time
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                required:
                  - error
                  - message
                properties:
                  error:
                    type: string
                  message:
                    type: string

  /users/{userId}:
    get:
      summary: Get a user by ID
      operationId: getUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  - username
                  - email
                properties:
                  id:
                    type: integer
                  username:
                    type: string
                  email:
                    type: string
                  age:
                    type: integer
                  createdAt:
                    type: string
                    format: date-time
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                required:
                  - error
                properties:
                  error:
                    type: string

    put:
      summary: Update a user
      operationId: updateUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  minLength: 3
                email:
                  type: string
                  format: email
                age:
                  type: integer
                  minimum: 13
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                type: object
                required:
                  - id
                  - username
                  - email
                properties:
                  id:
                    type: integer
                  username:
                    type: string
                  email:
                    type: string
                  age:
                    type: integer

    delete:
      summary: Delete a user
      operationId: deleteUser
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
        - name: x-api-key
          in: header
          required: true
          schema:
            type: string
      responses:
        '204':
          description: User deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
